# Generated by Django 5.0.6 on 2024-06-09 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardmessage_user_board_boardmessage_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessage',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
